Repository GlueOps/development-only-utilities, pull requests merged in 2024-10, with the labels that each got.

#43 feat: adding script to create config for AWS Extended Role Switcher chrome extension
  tools/aws/AWS-Extend-Switch-Roles-Configuration-Generator.py
  tools/aws/README.md
Labels: documentation, enhancement, include-in-release-notes, minor, patch, Review effort [1-5]: 2

#48 Major/remove set e
  tools/glueops-platform/deploy-argocd
  tools/glueops-platform/deploy-glueops-platform
Labels: include-in-release-notes, Review effort [1-5]: 2, major

#46 [skip actions] synced file(s) with internal-GlueOps/github-shared-files-sync
  .github/release.yml
Labels: Review effort [1-5]: 1, sync, configuration changes
